/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.igu;

import com.conversormonedas.Conversor;
import com.conversormonedas.Longitud;
import com.conversormonedas.Temperatura;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author lucia
 */
public class Portada extends javax.swing.JFrame {

    float entrada = 0;
    double cambio = 0;
    //ImageIcon img = new ImageIcon(image)
    Conversor conversor = new Conversor();
    Longitud longitud = new Longitud();
    Temperatura tmp = new Temperatura();
    DecimalFormat redondeo = new DecimalFormat("#0.000");
    

    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();

        setIconImage(getIconImage());
        
        
    }
    
    

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCambio = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        txtfValorCambio = new javax.swing.JTextField();
        cmbCambio = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        frmAcercaDe = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblChallenger = new javax.swing.JLabel();
        lblPor = new javax.swing.JLabel();
        lblLuciano = new javax.swing.JLabel();
        lblOracle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnMonedas = new javax.swing.JButton();
        btnTemperatura = new javax.swing.JButton();
        btnLongitud = new javax.swing.JButton();
        tpnlPrincipal = new javax.swing.JTabbedPane();
        pnlMonedas = new javax.swing.JPanel();
        btnConvertirMoneda = new javax.swing.JButton();
        cmbSalidaMoneda = new javax.swing.JComboBox<>();
        lblBanderaSalida = new javax.swing.JLabel();
        txtfEntrada = new javax.swing.JTextField();
        txtfSalida = new javax.swing.JTextField();
        lblBanderaEntrada = new javax.swing.JLabel();
        lblValorTexto = new javax.swing.JLabel();
        lblValorOficial = new javax.swing.JLabel();
        btnModifcarCambio = new javax.swing.JButton();
        cmbEntradaMoneda = new javax.swing.JComboBox<>();
        pnlTemperatura = new javax.swing.JPanel();
        btnConvertirTmp = new javax.swing.JButton();
        cmbEntradaTmp = new javax.swing.JComboBox<>();
        cmbSalidaTmp = new javax.swing.JComboBox<>();
        txtfEntradaTmp = new javax.swing.JTextField();
        txtfSalidaTmp = new javax.swing.JTextField();
        lblReferencia = new javax.swing.JLabel();
        lblEntradaTmp = new javax.swing.JLabel();
        lblSalidaTmp = new javax.swing.JLabel();
        pnlLongitud = new javax.swing.JPanel();
        cmbEntradaLong = new javax.swing.JComboBox<>();
        txtfEntradaLong = new javax.swing.JTextField();
        lblEntradaLong = new javax.swing.JLabel();
        lblReferenciaLong = new javax.swing.JLabel();
        btnConvertirLong = new javax.swing.JButton();
        cmbSalidaLong = new javax.swing.JComboBox<>();
        txtfSalidaLong = new javax.swing.JTextField();
        lblSalidaLong = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        dlgCambio.setTitle("Cambio Valor");
        dlgCambio.setEnabled(false);
        dlgCambio.setResizable(false);
        dlgCambio.setSize(new java.awt.Dimension(460, 250));
        dlgCambio.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Exo SemiBold", 0, 16)); // NOI18N
        jTextField1.setText("Peso Argentino");
        dlgCambio.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        txtfValorCambio.setEditable(false);
        txtfValorCambio.setFont(new java.awt.Font("Exo SemiBold", 0, 16)); // NOI18N
        txtfValorCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfValorCambio.setText("206.186");
        txtfValorCambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfValorCambioKeyTyped(evt);
            }
        });
        dlgCambio.getContentPane().add(txtfValorCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 100, 30));

        cmbCambio.setFont(new java.awt.Font("Exo SemiBold", 0, 16)); // NOI18N
        cmbCambio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar US$", "Euro €" }));
        cmbCambio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCambioItemStateChanged(evt);
            }
        });
        dlgCambio.getContentPane().add(cmbCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 153, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        jLabel2.setFont(new java.awt.Font("Exo SemiBold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Qué valor desa cambiar?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        dlgCambio.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 90));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        dlgCambio.getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        dlgCambio.getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        dlgCambio.getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        frmAcercaDe.setTitle("Acerca de...");
        frmAcercaDe.setBackground(new java.awt.Color(107, 0, 84));
        frmAcercaDe.setMaximumSize(new java.awt.Dimension(608, 250));
        frmAcercaDe.setMinimumSize(new java.awt.Dimension(608, 250));
        frmAcercaDe.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(57, 86, 100));

        lblChallenger.setFont(new java.awt.Font("Exo", 0, 18)); // NOI18N
        lblChallenger.setForeground(new java.awt.Color(246, 255, 229));
        lblChallenger.setText("Challenger Conversor de Monedas Alura");

        lblPor.setFont(new java.awt.Font("Exo Medium", 0, 12)); // NOI18N
        lblPor.setForeground(new java.awt.Color(246, 255, 229));
        lblPor.setText("por");

        lblLuciano.setFont(new java.awt.Font("Exo", 2, 14)); // NOI18N
        lblLuciano.setForeground(new java.awt.Color(246, 255, 229));
        lblLuciano.setText("Luciano Ezequiel Cuevas");

        lblOracle.setFont(new java.awt.Font("Exo SemiBold", 3, 30)); // NOI18N
        lblOracle.setForeground(new java.awt.Color(246, 255, 229));
        lblOracle.setText("ORACLE ONE Grupo 4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(lblPor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChallenger, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblOracle)
                        .addGap(158, 158, 158))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(lblLuciano, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblOracle)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblChallenger)
                .addGap(18, 18, 18)
                .addComponent(lblPor)
                .addGap(18, 18, 18)
                .addComponent(lblLuciano)
                .addContainerGap())
        );

        javax.swing.GroupLayout frmAcercaDeLayout = new javax.swing.GroupLayout(frmAcercaDe.getContentPane());
        frmAcercaDe.getContentPane().setLayout(frmAcercaDeLayout);
        frmAcercaDeLayout.setHorizontalGroup(
            frmAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frmAcercaDeLayout.setVerticalGroup(
            frmAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(51, 51, 51));

        lblTitulo.setFont(new java.awt.Font("Exo Medium", 0, 60)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CONVERSOR DE MONEDAS");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Logodark_1.png"))); // NOI18N

        btnMonedas.setBackground(new java.awt.Color(204, 204, 204));
        btnMonedas.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        btnMonedas.setText("Conversor Monedas");
        btnMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonedasActionPerformed(evt);
            }
        });

        btnTemperatura.setBackground(new java.awt.Color(255, 204, 51));
        btnTemperatura.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        btnTemperatura.setText("Conversor temperatura");
        btnTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturaActionPerformed(evt);
            }
        });

        btnLongitud.setBackground(new java.awt.Color(0, 204, 204));
        btnLongitud.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        btnLongitud.setText("Conversor longitud");
        btnLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLongitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblTitulo))
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCabeceraLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMonedas)
                    .addComponent(btnTemperatura)
                    .addComponent(btnLongitud))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 260));

        pnlMonedas.setBackground(new java.awt.Color(204, 204, 204));

        btnConvertirMoneda.setBackground(new java.awt.Color(51, 153, 0));
        btnConvertirMoneda.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        btnConvertirMoneda.setText("CONVERTIR");
        btnConvertirMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirMonedaActionPerformed(evt);
            }
        });

        cmbSalidaMoneda.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        cmbSalidaMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peso Argentino AR$", "Dolar US$", "EURO €", " ", " ", " " }));
        cmbSalidaMoneda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSalidaMonedaItemStateChanged(evt);
            }
        });
        cmbSalidaMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalidaMonedaActionPerformed(evt);
            }
        });

        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png"))); // NOI18N

        txtfEntrada.setFont(new java.awt.Font("Exo SemiBold", 3, 36)); // NOI18N
        txtfEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfEntrada.setText("1");
        txtfEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEntradaActionPerformed(evt);
            }
        });
        txtfEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfEntradaKeyTyped(evt);
            }
        });

        txtfSalida.setEditable(false);
        txtfSalida.setFont(new java.awt.Font("Exo SemiBold", 3, 36)); // NOI18N

        lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png"))); // NOI18N

        lblValorTexto.setFont(new java.awt.Font("Exo Light", 2, 32)); // NOI18N
        lblValorTexto.setText("Valor Oficial");

        lblValorOficial.setFont(new java.awt.Font("Exo Medium", 2, 32)); // NOI18N
        lblValorOficial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnModifcarCambio.setBackground(new java.awt.Color(51, 51, 51));
        btnModifcarCambio.setFont(new java.awt.Font("Exo", 0, 24)); // NOI18N
        btnModifcarCambio.setForeground(new java.awt.Color(255, 255, 255));
        btnModifcarCambio.setText("Modificar cambio");
        btnModifcarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifcarCambioActionPerformed(evt);
            }
        });

        cmbEntradaMoneda.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        cmbEntradaMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peso Argentino AR$", "Dolar US$", "EURO €", " ", " ", " " }));
        cmbEntradaMoneda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEntradaMonedaItemStateChanged(evt);
            }
        });
        cmbEntradaMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntradaMonedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMonedasLayout = new javax.swing.GroupLayout(pnlMonedas);
        pnlMonedas.setLayout(pnlMonedasLayout);
        pnlMonedasLayout.setHorizontalGroup(
            pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonedasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfEntrada)
                    .addComponent(lblBanderaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEntradaMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMonedasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConvertirMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonedasLayout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(btnModifcarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonedasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorTexto))
                        .addGap(72, 72, 72)))
                .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbSalidaMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBanderaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfSalida))
                .addGap(17, 17, 17))
        );
        pnlMonedasLayout.setVerticalGroup(
            pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonedasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMonedasLayout.createSequentialGroup()
                        .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConvertirMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEntradaMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMonedasLayout.createSequentialGroup()
                        .addComponent(cmbSalidaMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValorOficial, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMonedasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblBanderaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBanderaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMonedasLayout.createSequentialGroup()
                        .addComponent(lblValorTexto)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifcarCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tpnlPrincipal.addTab("tab1", pnlMonedas);

        pnlTemperatura.setBackground(new java.awt.Color(255, 204, 55));

        btnConvertirTmp.setBackground(new java.awt.Color(0, 102, 102));
        btnConvertirTmp.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        btnConvertirTmp.setForeground(new java.awt.Color(204, 255, 255));
        btnConvertirTmp.setText("Convertir");
        btnConvertirTmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirTmpActionPerformed(evt);
            }
        });

        cmbEntradaTmp.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        cmbEntradaTmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centigrados", "Farenheit", "Kelvin" }));
        cmbEntradaTmp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEntradaTmpItemStateChanged(evt);
            }
        });
        cmbEntradaTmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntradaTmpActionPerformed(evt);
            }
        });

        cmbSalidaTmp.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        cmbSalidaTmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centigrados", "Farenheit", "Kelvin" }));
        cmbSalidaTmp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSalidaTmpItemStateChanged(evt);
            }
        });

        txtfEntradaTmp.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        txtfEntradaTmp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfEntradaTmp.setText("1");
        txtfEntradaTmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfEntradaTmpKeyTyped(evt);
            }
        });

        txtfSalidaTmp.setEditable(false);
        txtfSalidaTmp.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        txtfSalidaTmp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfSalidaTmp.setText("1");

        lblReferencia.setFont(new java.awt.Font("Exo Medium", 0, 32)); // NOI18N
        lblReferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReferencia.setText("1");

        lblEntradaTmp.setFont(new java.awt.Font("Exo Medium", 0, 32)); // NOI18N
        lblEntradaTmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntradaTmp.setText("C°");

        lblSalidaTmp.setFont(new java.awt.Font("Exo Medium", 0, 32)); // NOI18N
        lblSalidaTmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalidaTmp.setText("C°");

        javax.swing.GroupLayout pnlTemperaturaLayout = new javax.swing.GroupLayout(pnlTemperatura);
        pnlTemperatura.setLayout(pnlTemperaturaLayout);
        pnlTemperaturaLayout.setHorizontalGroup(
            pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTemperaturaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEntradaTmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfEntradaTmp)
                    .addComponent(cmbEntradaTmp, 0, 266, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConvertirTmp, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfSalidaTmp)
                    .addComponent(cmbSalidaTmp, 0, 253, Short.MAX_VALUE)
                    .addComponent(lblSalidaTmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnlTemperaturaLayout.setVerticalGroup(
            pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTemperaturaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEntradaTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSalidaTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertirTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfSalidaTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfEntradaTmp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReferencia))
                .addGap(38, 38, 38)
                .addGroup(pnlTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEntradaTmp)
                    .addComponent(lblSalidaTmp))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tpnlPrincipal.addTab("tab2", pnlTemperatura);

        pnlLongitud.setBackground(new java.awt.Color(0, 204, 204));

        cmbEntradaLong.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        cmbEntradaLong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metro", "Kilometro", "Milla" }));
        cmbEntradaLong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEntradaLongItemStateChanged(evt);
            }
        });

        txtfEntradaLong.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        txtfEntradaLong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfEntradaLong.setText("1");
        txtfEntradaLong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfEntradaLongKeyTyped(evt);
            }
        });

        lblEntradaLong.setFont(new java.awt.Font("Exo Medium", 0, 32)); // NOI18N
        lblEntradaLong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntradaLong.setText("m");

        lblReferenciaLong.setFont(new java.awt.Font("Exo Medium", 0, 32)); // NOI18N
        lblReferenciaLong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReferenciaLong.setText("1");

        btnConvertirLong.setBackground(new java.awt.Color(0, 0, 102));
        btnConvertirLong.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        btnConvertirLong.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertirLong.setText("Convertir");
        btnConvertirLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirLongActionPerformed(evt);
            }
        });

        cmbSalidaLong.setFont(new java.awt.Font("Exo Medium", 0, 24)); // NOI18N
        cmbSalidaLong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metro", "Kilometro", "Milla" }));
        cmbSalidaLong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSalidaLongItemStateChanged(evt);
            }
        });

        txtfSalidaLong.setEditable(false);
        txtfSalidaLong.setFont(new java.awt.Font("Exo SemiBold", 0, 24)); // NOI18N
        txtfSalidaLong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfSalidaLong.setText("1");

        lblSalidaLong.setFont(new java.awt.Font("Exo Medium", 0, 32)); // NOI18N
        lblSalidaLong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalidaLong.setText("m");

        javax.swing.GroupLayout pnlLongitudLayout = new javax.swing.GroupLayout(pnlLongitud);
        pnlLongitud.setLayout(pnlLongitudLayout);
        pnlLongitudLayout.setHorizontalGroup(
            pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLongitudLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEntradaLong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfEntradaLong)
                    .addComponent(cmbEntradaLong, 0, 266, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConvertirLong, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblReferenciaLong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfSalidaLong)
                    .addComponent(cmbSalidaLong, 0, 253, Short.MAX_VALUE)
                    .addComponent(lblSalidaLong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnlLongitudLayout.setVerticalGroup(
            pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLongitudLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEntradaLong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSalidaLong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertirLong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfSalidaLong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfEntradaLong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReferenciaLong))
                .addGap(38, 38, 38)
                .addGroup(pnlLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEntradaLong)
                    .addComponent(lblSalidaLong))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        tpnlPrincipal.addTab("tab3", pnlLongitud);

        getContentPane().add(tpnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, 900, 360));

        Menu.setText("Acerca de...");

        jMenuItem1.setText("Acerca del programa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem1);

        mbMenu.add(Menu);

        setJMenuBar(mbMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSalidaMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalidaMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSalidaMonedaActionPerformed

    private void txtfEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEntradaActionPerformed

    private void btnConvertirMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirMonedaActionPerformed

        entrada = Float.parseFloat(txtfEntrada.getText());

        int i = cmbEntradaMoneda.getSelectedIndex();
        int j = cmbSalidaMoneda.getSelectedIndex();
        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        //lblBanderaSalida.setIcon(ge BanderaArgentina.png);
                        lblValorOficial.setText("1");
                        txtfSalida.setText(String.valueOf(entrada));
                        break;
                    case 1:
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.getDolar())));
                        txtfSalida.setText(String.valueOf(redondeo.format(conversor.pesodolar(entrada))));
                        break;
                    case 2:
                        lblValorOficial.setText(String.valueOf(conversor.getEuro()));
                        txtfSalida.setText(String.valueOf(redondeo.format(conversor.pesoeuro(entrada))));
                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        //lblBanderaSalida.setIcon(ge BanderaArgentina.png);
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.dolarpeso(1))));
                        txtfSalida.setText(String.valueOf(redondeo.format(conversor.dolarpeso(entrada))));
                        break;
                    case 1:
                        lblValorOficial.setText("1");
                        txtfSalida.setText(String.valueOf(entrada));
                        break;
                    case 2:
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.dolareuro(1))));
                        txtfSalida.setText(String.valueOf(redondeo.format(conversor.dolareuro(entrada))));
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        //lblBanderaSalida.setIcon(getClass().getResource("/com.imagenes/BanderaArgentina.png"));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.getPeso() / conversor.getEuro())));
                        txtfSalida.setText(String.valueOf(redondeo.format(conversor.europeso(entrada))));
                        break;
                    case 1:
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.eurodolar(1))));
                        txtfSalida.setText(String.valueOf(redondeo.format(conversor.eurodolar(entrada))));
                        break;
                    case 2:
                        lblValorOficial.setText("1");
                        txtfSalida.setText(String.valueOf(redondeo.format(entrada)));
                        break;
                }
                break;
        }
    }//GEN-LAST:event_btnConvertirMonedaActionPerformed

    private void cmbEntradaMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntradaMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntradaMonedaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dlgCambio.setEnabled(false);
        dlgCambio.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        txtfValorCambio.setEditable(true);
        cambio = Double.parseDouble(txtfValorCambio.getText());

        switch (cmbCambio.getSelectedIndex()) {
            case 0:
                conversor.setDolar(cambio);
                break;
            case 1:
                conversor.setEuro(cambio);
                break;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnModifcarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifcarCambioActionPerformed

        dlgCambio.setEnabled(true);
        dlgCambio.setVisible(true);
        dlgCambio.setLocationRelativeTo(null);

// TODO add your handling code here:
    }//GEN-LAST:event_btnModifcarCambioActionPerformed

    private void cmbCambioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCambioItemStateChanged

        switch (cmbCambio.getSelectedIndex()) {
            case 0:
                txtfValorCambio.setText(String.valueOf(redondeo.format(conversor.dolarpeso(1))));
                break;
            case 1:
                txtfValorCambio.setText(String.valueOf(redondeo.format(conversor.europeso(1))));
                break;
        }

    }//GEN-LAST:event_cmbCambioItemStateChanged

    private void cmbSalidaMonedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSalidaMonedaItemStateChanged
        int i = cmbEntradaMoneda.getSelectedIndex();
        int j = cmbSalidaMoneda.getSelectedIndex();

        switch (i) {
            case 0:
                lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                switch (j) {
                    case 0:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                        lblValorOficial.setText("1");
                        break;
                    case 1:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.getDolar())));
                        break;
                    case 2:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                        lblValorOficial.setText(String.valueOf(conversor.getEuro()));
                        break;
                }
                break;
            case 1:
                lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                switch (j) {
                    case 0:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.dolarpeso(1))));
                        break;
                    case 1:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                        lblValorOficial.setText("1");
                        txtfSalida.setText(String.valueOf(entrada));
                        break;
                    case 2:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.dolareuro(1))));
                        break;
                }
                break;
            case 2:
                lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                switch (j) {
                    case 0:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.getPeso() / conversor.getEuro())));
                        break;
                    case 1:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.eurodolar(1))));
                        break;
                    case 2:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                        lblValorOficial.setText("1");
                        break;
                }
                break;

        }
    }//GEN-LAST:event_cmbSalidaMonedaItemStateChanged

    private void cmbEntradaMonedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEntradaMonedaItemStateChanged

        int i = cmbEntradaMoneda.getSelectedIndex();
        int j = cmbSalidaMoneda.getSelectedIndex();

        switch (i) {
            case 0:
                lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                switch (j) {
                    case 0:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                        lblValorOficial.setText("1");
                        break;
                    case 1:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.getDolar())));
                        break;
                    case 2:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                        lblValorOficial.setText(String.valueOf(conversor.getEuro()));
                        break;
                }
                break;
            case 1:
                lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                switch (j) {
                    case 0:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.dolarpeso(1))));
                        break;
                    case 1:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                        lblValorOficial.setText("1");
                        txtfSalida.setText(String.valueOf(entrada));
                        break;
                    case 2:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.dolareuro(1))));
                        break;
                }
                break;
            case 2:
                lblBanderaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                switch (j) {
                    case 0:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaArgentina.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.getPeso() / conversor.getEuro())));
                        break;
                    case 1:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaUsa.png")));
                        lblValorOficial.setText(String.valueOf(redondeo.format(conversor.eurodolar(1))));
                        break;
                    case 2:
                        lblBanderaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/BanderaEuro.png")));
                        lblValorOficial.setText("1");
                        break;
                }
                break;

        }

    }//GEN-LAST:event_cmbEntradaMonedaItemStateChanged

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        txtfValorCambio.setEditable(false);
        cambio = Double.parseDouble(txtfValorCambio.getText());

        switch (cmbCambio.getSelectedIndex()) {
            case 0:
                conversor.setDolar(cambio);
                break;
            case 1:
                conversor.setEuro(cambio);
                break;
        }
        JOptionPane.showMessageDialog(null, "Se realizo el cambio, nuevo valor: " + cambio, "Se guardaron los cambios", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtfEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfEntradaKeyTyped

        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            JOptionPane.showMessageDialog(null, "Solo numeros", "¡Error!", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfEntradaKeyTyped

    private void txtfValorCambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfValorCambioKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            JOptionPane.showMessageDialog(null, "Solo numeros", "¡Error!", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtfValorCambioKeyTyped

    private void btnMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonedasActionPerformed

        tpnlPrincipal.setSelectedIndex(0);

    }//GEN-LAST:event_btnMonedasActionPerformed

    private void btnTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperaturaActionPerformed
        tpnlPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnTemperaturaActionPerformed

    private void btnLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLongitudActionPerformed
        tpnlPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_btnLongitudActionPerformed

    private void cmbSalidaTmpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSalidaTmpItemStateChanged

        //guardo en una variable float la entrada del usuario
        entrada = Float.parseFloat(txtfEntrada.getText());

        //Guardo los el indice del item selecionado tanto en el 
        //combo box de entrada como de salida
        int i = cmbEntradaTmp.getSelectedIndex();
        int j = cmbSalidaTmp.getSelectedIndex();
        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("C°");
                        break;
                    case 1:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("F°");
                        break;
                    case 2:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("K°");
                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("C°");
                        break;
                    case 1:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("F°");
                        break;
                    case 2:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("K°");
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("C°");
                        break;
                    case 1:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("F°");
                        break;
                    case 2:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("K°");
                        break;
                }
                break;
        }

    }//GEN-LAST:event_cmbSalidaTmpItemStateChanged

    private void txtfEntradaTmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfEntradaTmpKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key != 47 && key >= 44 && key <= 57;

        if (!numeros) {
            JOptionPane.showMessageDialog(null, "Solo numeros", "¡Error!", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtfEntradaTmpKeyTyped

    private void txtfEntradaLongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfEntradaLongKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key != 47 && key >= 44 && key <= 57;

        if (!numeros) {
            JOptionPane.showMessageDialog(null, "Solo numeros", "¡Error!", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_txtfEntradaLongKeyTyped

    private void btnConvertirTmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirTmpActionPerformed
        
        //guardo en una variable float la entrada del usuario
        entrada = Float.parseFloat(txtfEntradaTmp.getText());

        int i = cmbEntradaTmp.getSelectedIndex();
        int j = cmbSalidaTmp.getSelectedIndex();

        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("C°");
                        txtfSalidaTmp.setText(String.valueOf(entrada));
                        break;
                    case 1:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("F°");
                        txtfSalidaTmp.setText(String.valueOf(redondeo.format(tmp.centigradosFarenheit(entrada))));
                        break;
                    case 2:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("K°");
                        txtfSalidaTmp.setText(String.valueOf(redondeo.format(tmp.centigradosKelvin(entrada))));
                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("C°");
                        txtfSalidaTmp.setText(String.valueOf(redondeo.format(tmp.farenheitCentigrados(entrada))));
                        break;
                    case 1:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("F°");
                        txtfSalidaTmp.setText(String.valueOf((entrada)));
                        break;
                    case 2:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("K°");
                        txtfSalidaTmp.setText(String.valueOf(redondeo.format(tmp.farenheitKelvin(entrada))));
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("C°");
                        txtfSalidaTmp.setText(String.valueOf(redondeo.format(tmp.kelvinCentigrados(entrada))));
                        break;
                    case 1:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("F°");
                        txtfSalidaTmp.setText(String.valueOf(redondeo.format(tmp.kelvinFarenheit(entrada))));
                        break;
                    case 2:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("K°");
                        txtfSalidaTmp.setText(String.valueOf(entrada));
                        break;
                }
                break;
        }
    }//GEN-LAST:event_btnConvertirTmpActionPerformed

    private void cmbEntradaTmpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEntradaTmpItemStateChanged
        //guardo en una variable float la entrada del usuario
        entrada = Float.parseFloat(txtfEntrada.getText());

        int i = cmbEntradaTmp.getSelectedIndex();
        int j = cmbSalidaTmp.getSelectedIndex();

        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("C°");

                        break;
                    case 1:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("F°");

                        break;
                    case 2:
                        lblEntradaTmp.setText("C°");
                        lblSalidaTmp.setText("K°");

                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("C°");
                        break;
                    case 1:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("F°");
                        break;
                    case 2:
                        lblEntradaTmp.setText("F°");
                        lblSalidaTmp.setText("K°");
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("C°");
                        break;
                    case 1:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("F°");
                        break;
                    case 2:
                        lblEntradaTmp.setText("K°");
                        lblSalidaTmp.setText("K°");
                        break;
                }
                break;
        }
    }//GEN-LAST:event_cmbEntradaTmpItemStateChanged

    private void cmbSalidaLongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSalidaLongItemStateChanged
        entrada = Float.parseFloat(txtfEntrada.getText());

        int i = cmbEntradaLong.getSelectedIndex();
        int j = cmbSalidaLong.getSelectedIndex();

        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("m");
                        break;
                    case 1:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("km");
                        break;
                    case 2:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("mi");
                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("m");
                        break;
                    case 1:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("km");
                        break;
                    case 2:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("mi");
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("m");
                        break;
                    case 1:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("km");
                        break;
                    case 2:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("mi");
                        break;
                }
                break;
        }
    }//GEN-LAST:event_cmbSalidaLongItemStateChanged

    private void cmbEntradaLongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEntradaLongItemStateChanged
        entrada = Float.parseFloat(txtfEntradaLong.getText());
        int i = cmbEntradaLong.getSelectedIndex();
        int j = cmbSalidaLong.getSelectedIndex();

        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("m");
                        break;
                    case 1:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("km");
                        break;
                    case 2:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("mi");
                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("m");
                        break;
                    case 1:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("km");
                        break;
                    case 2:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("mi");
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("m");
                        break;
                    case 1:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("km");
                        break;
                    case 2:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("mi");
                        break;
                }
                break;
        }
    }//GEN-LAST:event_cmbEntradaLongItemStateChanged

    private void btnConvertirLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirLongActionPerformed
        
        //guardo en una variable float la entrada del usuario
        entrada = Float.parseFloat(txtfEntradaLong.getText());

        int i = cmbEntradaLong.getSelectedIndex();
        int j = cmbSalidaLong.getSelectedIndex();

        switch (i) {
            case 0:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("m");
                        txtfSalidaLong.setText(String.valueOf(txtfEntradaLong.getText()));
                        break;
                    case 1:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("km");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(longitud.metroKm(entrada))));
                        break;
                    case 2:
                        lblEntradaLong.setText("m");
                        lblSalidaLong.setText("mi");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(longitud.metroMilla(entrada))));
                        break;
                }
                break;
            case 1:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("m");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(longitud.kmMetro(entrada))));
                        break;
                    case 1:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("km");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(txtfEntradaLong.getText())));
                        break;
                    case 2:
                        lblEntradaLong.setText("km");
                        lblSalidaLong.setText("mi");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(longitud.kmMilla(entrada))));
                        break;
                }
                break;
            case 2:
                switch (j) {
                    case 0:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("m");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(longitud.millaMetro(entrada))));
                        break;
                    case 1:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("km");
                        txtfSalidaLong.setText(String.valueOf(redondeo.format(longitud.millaKm(entrada))));
                        break;
                    case 2:
                        lblEntradaLong.setText("mi");
                        lblSalidaLong.setText("mi");
                        txtfSalidaLong.setText(String.valueOf(txtfEntradaLong.getText()));
                        break;
                }
                break;
        }
    }//GEN-LAST:event_btnConvertirLongActionPerformed

    private void cmbEntradaTmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntradaTmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntradaTmpActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Hago Visible formulario de info del programa
        frmAcercaDe.setVisible(true);
        frmAcercaDe.setLocationRelativeTo(null);
        frmAcercaDe.setIconImage(getIconImage());//setIconImage(getIconImage());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConvertirLong;
    private javax.swing.JButton btnConvertirMoneda;
    private javax.swing.JButton btnConvertirTmp;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLongitud;
    private javax.swing.JButton btnModifcarCambio;
    private javax.swing.JButton btnMonedas;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JComboBox<String> cmbCambio;
    private javax.swing.JComboBox<String> cmbEntradaLong;
    private javax.swing.JComboBox<String> cmbEntradaMoneda;
    private javax.swing.JComboBox<String> cmbEntradaTmp;
    private javax.swing.JComboBox<String> cmbSalidaLong;
    private javax.swing.JComboBox<String> cmbSalidaMoneda;
    private javax.swing.JComboBox<String> cmbSalidaTmp;
    private javax.swing.JDialog dlgCambio;
    private javax.swing.JFrame frmAcercaDe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBanderaEntrada;
    private javax.swing.JLabel lblBanderaSalida;
    private javax.swing.JLabel lblChallenger;
    private javax.swing.JLabel lblEntradaLong;
    private javax.swing.JLabel lblEntradaTmp;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLuciano;
    private javax.swing.JLabel lblOracle;
    private javax.swing.JLabel lblPor;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblReferenciaLong;
    private javax.swing.JLabel lblSalidaLong;
    private javax.swing.JLabel lblSalidaTmp;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorOficial;
    private javax.swing.JLabel lblValorTexto;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlLongitud;
    private javax.swing.JPanel pnlMonedas;
    private javax.swing.JPanel pnlTemperatura;
    private javax.swing.JTabbedPane tpnlPrincipal;
    private javax.swing.JTextField txtfEntrada;
    private javax.swing.JTextField txtfEntradaLong;
    private javax.swing.JTextField txtfEntradaTmp;
    private javax.swing.JTextField txtfSalida;
    private javax.swing.JTextField txtfSalidaLong;
    private javax.swing.JTextField txtfSalidaTmp;
    private javax.swing.JTextField txtfValorCambio;
    // End of variables declaration//GEN-END:variables
}
